version: "2"

services:
  website:
    build: .
    command: >
      uvicorn
      --host 0.0.0.0
      --port 8000
      --reload
      "app.main:app"
    volumes:
      - ".:/app"
    ports:
      - "8000:8000"
