version: "2"

services:
  website:
    container_name: vest_challenge
    build: .
    command: >
      uvicorn
      --host 0.0.0.0
      --port 8000
      --reload
      "main:app"
    volumes:
      - "./app:/app"
    ports:
      - "8000:8000"